[package]
name = "get-link"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["blocking"] }
scraper = "0.23.1"
url = "2.5.4"
